version: '3'

services:
  prodxcloud-dev:
    container_name: prodxcloud-dev
    image: joelwembo/prodxcloud-dev:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"  
    volumes:
      - ./nginx/dev/default.conf:/etc/nginx/conf.d/default.conf
      - prodxcloud-dev-data:/usr/share/nginx/html
      
    networks:
      - prodxcloud-net

networks:
  prodxcloud-net:
    driver: bridge

volumes:
  prodxcloud-dev-data:      